import './globals.css'
import {  Mulish } from 'next/font/google'
import Header from './components/Header'
import Footer from './components/Footer'

const mulish = Mulish({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
  return (
    <html lang="en" className={mulish.className}>
      <body >
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
